# Generated by Django 5.1.3 on 2024-12-23 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("modified_at", models.DateField(auto_now=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users/profile_pictures",
                    ),
                ),
                (
                    "cover_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="users/cover_photo"
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "pin_code",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
                (
                    "latitude",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "longitude",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
